name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup_python@v1
      with:
        python-version: "3.8"
    - name: Build Extra Documentation Files
      run: python "source/build.py"
